name='张三'
age=20
a=b=c=d=100
a,b,c,d='room'
print(a,b,c,d)
print('输入/输出语句')
name=input('请输入您的姓名：')
age=eval(input('请输入您的年龄：'))
lucky_number=eval(input('请输入您的幸运数字：'))
print('姓名：',name)
print('年龄：',age)
print('幸运数字：',lucky_number)