print('123'.isdigit())
print('一二三'.isdigit())
print('0b1010'.isdigit())
print('ⅢⅢⅢ'.isdigit())
print('-'*50)
print('123'.isnumeric())
print('一二三'.isnumeric())
print('0b1010'.isnumeric())
print('ⅢⅢⅢ'.isnumeric())
print('壹贰叁'.isnumeric())

print('-'*50)
print('hello你好'.isalpha())
print('hellow你好123'.isalpha())
print('hello你好一二三'.isalpha())
print('hello你好ⅢⅢⅢ'.isalpha())
print('-'*50)
print('hello你好'.isalnum())
print('hellow你好123'.isalnum())
print('hello你好一二三'.isalnum())
print('hello你好ⅢⅢⅢ'.isalnum())

print('-'*50)
print('HelloWorld'.islower())
print('helloworld'.islower())
print('hello你好'.islower())
print('-'*50)
print('HelloWorld'.isupper())
print('HELLOWORLD'.isupper())
print('HELLO你好'.isupper())
print('-'*50)
print('Hello'.istitle())
print('HelloWorld'.istitle())
print('Helloworld'.istitle())
print('Hello World'.istitle())
print('Hello world'.istitle())
print('-'*50)
print('\t'.isspace())
print(' '.isspace())
print('\n'.isspace())
print('\r'.isspace())
